#!/usr/bin/env python

# checks that the files here only differ from the "real" python in commented out bits

import sys
import os

BASE = "../python-30rc2"

for path, dirs, files in os.walk("."):
    for filename in files:
        line_num = 0
        commented = 0
        changed = 0
        exact = 0
        
        if filename[-2:] not in [".c", ".h"]:
            continue
        ours = os.path.join(path, filename)
        theirs = os.path.join(BASE, path, filename)
        if not os.access(theirs, os.F_OK):
            print "no file corresponding: %s" % ours
            sys.exit(1)
        for our_line, their_line in zip(open(ours), open(theirs)):
            line_num += 1
            if our_line == their_line:
                # we've included their line
                exact += 1
            elif our_line == "// " + their_line:
                # we've commented out their line
                commented += 1
            elif "// " in our_line and our_line.split("// ")[1] == their_line.lstrip():
                # we've changed their line
                changed += 1
            else:
                print "in file %s (line %d), the following lines are inconsistent:" % (ours, line_num)
                print our_line, their_line
                sys.exit(2)
        total = commented + changed + exact
        print "%40s\t%d\t%d\t%d\t%s%%\t%d" % (ours, commented, changed, exact, (100 * exact / total), total)