#!/usr/bin/env python

import sys
import os

if len(sys.argv) != 2:
    print "looks for file in ../python-30rc2 and copies a commented out version to the corresponding place under ."
    print "usage: %s <filename>" % sys.argv[0]
    sys.exit(1)

filename = sys.argv[1]

BASE = "../python-30rc2"

sources = []
for d in ["Include", "Modules", "Python"]:
    path = os.path.join(BASE, d, filename)
    if os.access(path, os.R_OK):
        sources.append(d)

if len(sources) == 0:
    print "file not found: %s" % filename
    sys.exit(2)

if len(sources) > 1:
    print "ambiguity: %s" % sources
    sys.exit(3)

source = os.path.join(BASE, sources[0], filename)
destination = os.path.join(".", sources[0], filename)

dest_file = open(destination, "w")
for line in open(source):
    dest_file.write("// " + line)
dest_file.close()

print "done: %s" % destination
